CREATE TABLE USER
(
    ID      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR (30) NOT NULL ,
    SURNAME VARCHAR (30) NOT NULL ,
    EMAIL   VARCHAR (30) NOT NULL ,
    AGE     INT (10) NOT NULL
);

CREATE TABLE ROLE
(
    ID   INT NOT NULL AUTO_INCREMENT,
    ROLE VARCHAR (10) NOT NULL
);


CREATE TABLE AUTHENTICATE
(
    ID      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN          VARCHAR (30) NOT NULL,
    PASSWORD       VARCHAR (30) NOT NULL,
    ROLEID INT NOT NULL DEFAULT 2,
    PROFILE_ENABLE VARCHAR NOT NULL  DEFAULT 'ON',
    FOREIGN KEY(ROLEID) REFERENCES ROLE(ID)
);



CREATE TABLE USERSROLES
(
    ID      INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL ,
    ROLE_ID INT NOT NULL
);

INSERT INTO USER (NAME, SURNAME, EMAIL, AGE)
VALUES ('IVAN', 'IVANOV', 'IVANOV@MAIL.RU', 18);
INSERT INTO USER (NAME, SURNAME, EMAIL, AGE)
VALUES ('PETR', 'PETROV', 'PETROV@MAIL.RU', 19);

INSERT INTO ROLE (ROLE)
VALUES ('ADMIN');
INSERT INTO ROLE (ROLE)
VALUES ('USER');



INSERT INTO AUTHENTICATE (LOGIN, PASSWORD, PROFILE_ENABLE)
VALUES ('ADMIN', '12', 'ON');
INSERT INTO AUTHENTICATE (LOGIN, PASSWORD, PROFILE_ENABLE)
VALUES ('ADMIN1', '121', 'ON');



INSERT INTO USERSROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERSROLES (USER_ID, ROLE_ID) VALUES (2, 1);

