INSERT INTO USER (NAME, SURNAME, EMAIL, AGE)
VALUES ('IVAN', 'IVANOV', 'IVANOV@MAIL.RU', 18);
INSERT INTO USER (NAME, SURNAME, EMAIL, AGE)
VALUES ('PETR', 'PETROV', 'PETROV@MAIL.RU', 19);

INSERT INTO ROLE (ROLE)
VALUES ('ADMIN');
INSERT INTO ROLE (ROLE)
VALUES ('USER');



INSERT INTO AUTHENTICATE (LOGIN, PASSWORD, PROFILE_ENABLE)
VALUES ('ADMIN', '12', 'ON');
INSERT INTO AUTHENTICATE (LOGIN, PASSWORD, PROFILE_ENABLE)
VALUES ('ADMIN1', '121', 'ON');



INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);

